:Author: harsha14
:Email: {AuthorEmail}
:Date: 06/03/2024
:Revision: version#
:License: Public Domain

= Project: Effective Usage of IoT Sensors on Stadiums for Monitoring & Predicting the Moisture Level Using AI

To develop a system to predict the soil moisture levels inside a cricket stadium by integrating IoT sensors with AI.

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch onto your board

=== Folder structure

....
 sketch123                                         => Arduino sketch folder
  ├── sketch_mar6a.ino                             => main Arduino file
  ├── Pin diagram of Arduino BLE 33 Sense.png      => an image of the required schematics
  ├── Overview of Hardware Setup.png               => an image of the layout
  └── ReadMe.adoc                                  => this file
....

=== License
This project is released under a {License} License.


|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10
| L1 | Red LED        | 2345-asdf   | 5
| A1 | Arduino Zero   | ABX00066    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
